### ISSUE TITLE
Form model

### ISSUE THREAD

**Issue by AmirMehrabian** [Quroup5/QForm#3]
I believe that the category field in the model of the form should have a True null property.

**Comment by ahmadrv** [comment]
You're right. I fixed it. Thanks for your comment.

**Comment by AmirMehrabian** [comment]
Hello again, thanks for your consideration.
In line 26 of forms/model.py, if user do not pass a password:
self.password=None,
and <<self.password.startswith >> creates a bug.

It needs a << if self.password is not None: >> statement in the previous line.

**Comment by ahmadrv** [comment]
Nice. It's done!
